### PR TITLE
CHK-4407, CHK4408: Remove Dependency on Base Checkout Extension

### PR DESCRIPTION
**Pull request by JosephLeedy**
Relates to [CHK-4407](https://boldapps.atlassian.net/browse/CHK-4407), [CHK-4408](https://boldapps.atlassian.net/browse/CHK-4408)

[CHK-4407]: https://boldapps.atlassian.net/browse/CHK-4407?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CHK-4408]: https://boldapps.atlassian.net/browse/CHK-4408?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by nicolenorman — APPROVED** [review]

**Review by nicolenorman — CHANGES_REQUESTED** [review]
I pulled these changes down and they seem to have broken my local. Want to confirm that this is isolated to my environment and these changes are working on your side without the core checkout module installed?

**Review by nicolenorman — COMMENTED** [review]
Poked around this for a bit and I think the issue is that the `Result` model isn't implementing the interface yet. That plus adding a preference to the di.xml fixed it on my local!

**Comment by JosephLeedy** [comment]
> I pulled these changes down and they seem to have broken my local. Want to confirm that this is isolated to my environment and these changes are working on your side without the core checkout module installed?

I didn't test them without the base Checkout extension installed. Good call-out!

> Poked around this for a bit and I think the issue is that the `Result` model isn't implementing the interface yet. That plus adding a preference to the di.xml fixed it on my local!

Thank you for calling out the missing preference. I'll get that added.

**Comment by JosephLeedy** [comment]
Regarding the preference, the base Checkout extension does not have one because they have several concrete implementations of the interface. If you look at [di.xml](https://github.com/bold-commerce/adobe-commerce-bold-checkout-payment-booster/blob/express-pay/etc/di.xml#L123-L139), you'll see that I'm explicitly overriding the implementation used for my classes.

**Comment by JosephLeedy** [comment]
My apologies, I thought that you were referring to the Bold HTTP Client. I didn't read closely enough to realize that you were talking about the Result object. I'll get that fixed. 😳

**Review by nicolenorman — APPROVED** [review]
Looks great! Your latest changes fixed the errors I had been seeing earlier, thank you!

**Pull request merged**
