### PR TITLE
CHK-4407, CHK-4408: Fix Bugs in Express Pay API Endpoints

### PR DESCRIPTION
**Pull request by JosephLeedy**
Fixes [CHK-4407](https://boldapps.atlassian.net/browse/CHK-4407), [CHK-4408](https://boldapps.atlassian.net/browse/CHK-4408)

[CHK-4407]: https://boldapps.atlassian.net/browse/CHK-4407?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CHK-4408]: https://boldapps.atlassian.net/browse/CHK-4408?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by nicolenorman — COMMENTED** [review]
This looks great! I'll pull this down today and test with my frontend callback logic

**Review by nicolenorman — COMMENTED** [review]
Just looking at your latest code changes all looks good.

I pulled this down locally to test but I think this branch must be based on a commit from before we removed the core checkout module dependencies as I'm getting errors about that again.

**Comment by JosephLeedy** [comment]
> I pulled this down locally to test but I think this branch must be based on a commit from before we removed the core checkout module dependencies as I'm getting errors about that again.

It was based off of the `express-pay` branch, so it _should_ have those changes. I'll verify that.

**Review by nicolenorman — APPROVED** [review]
Rebased this locally on top of the express-pay branch and everything worked great! Added one tiny commit to fix one small issue I came across with empty address and the empty selected shipping data. Feel free to make adjustments to it

**Pull request merged**
